# Generated by Django 5.0 on 2025-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staff_address_staff_dob_staff_email_staff_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
