# Generated by Django 5.0 on 2025-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_staff_role_staff_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
