# Generated by Django 5.0 on 2025-08-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='gender',
        ),
    ]
