# Generated by Django 5.0 on 2025-08-07 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='DA 20%')),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRA 50%')),
                ('conveyance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Conveyance 5%')),
                ('medical', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Medical Expenses 4%')),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Special 25%')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonus 44%')),
                ('ta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TA 2%')),
                ('pf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PF 12%')),
                ('professional_tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Professional Tax')),
                ('tds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TDS')),
                ('salary_advance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary Advance')),
                ('date', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
            ],
        ),
    ]
