# Generated by Django 5.0 on 2025-08-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_salaryrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='basic_salary',
        ),
        migrations.AddField(
            model_name='staff',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bonus 44%'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='conveyance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Conveyance 5%'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='da',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DA 20%'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='hra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='HRA 50%'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='medical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Medical Expenses 4%'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='pf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PF 12%'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='professional_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Professional Tax'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='salary_advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary Advance'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='special_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Special 25%'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='ta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TA 2%'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='tds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TDS'),
        ),
    ]
