# Generated by Django 5.0 on 2025-08-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_salaryrecord_basic_salary_staff_basic_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='conveyance',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='ta',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='tds',
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='special_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Special Allowance 25%'),
        ),
    ]
