# Generated by Django 5.0 on 2025-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_salaryrecord_conveyance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='da',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='special_allowance',
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='salary_advance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Salary Advance'),
        ),
    ]
