# Generated by Django 5.0 on 2025-08-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_salaryrecord_da_remove_salaryrecord_hra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='esi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='ESI 1.75%'),
        ),
    ]
