# Generated by Django 5.0 on 2025-08-13 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customer_district_customer_pincode_customer_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
